### ISSUE TITLE
Pint glass or mason jar

### ISSUE THREAD

**Issue by jywarren** [publiclab/design#1]
silicone: flexible, any color, monochrome insignia

Becki: I'm thinking about moving from the Silicon pint glass to a mason jar with cork coozie made by this fellow, still need a design. Sample here: http://instagram.com/p/sDBKbzmGcO/?modal=true

---

Becki: Silicone pint glass ($50 level, color and print options are included in the attachment. Black logo on white glass, white on black? Logo version? Heeeelp)

![screen shot 2014-09-23 at 2 57 27 pm](https://cloud.githubusercontent.com/assets/24359/4377943/a998daa2-4353-11e4-825e-4f38015f4b53.png)
![screen shot 2014-09-23 at 2 57 46 pm](https://cloud.githubusercontent.com/assets/24359/4377942/a9960426-4353-11e4-8f8e-2dda110db965.png)

**Comment by jywarren** [comment]
Liz, can you add a double hyphen and a space above your sig line so your emails don't leave a sig on Github? Thanks! 

Probably going to be a mason jar, it seems.

**Comment by ebarry** [comment]
+1 mason jar! Can we just use our regular logo, the circle with the boots?

**Comment by jywarren** [comment]
I'd like to get the hand-drawn one out there -- folks say they look too much like socks but I think I can edit that, also @BeckiC wanted a puddle in it. I can rework and that should do it.

**Comment by BeckiC** [comment]
Update: So of course mason jar guy emailed me back right after I said he'd been unresponsive. I'll take a look at price points and quantities and make a final call--artwork can be the same either way.

[The mason jar guy is being super unresponsive so don't anyone get their hopes up. They're very cool and I'll try to ping him again but I also don't want to spend a bunch of time tracking him down to get him to work on this for us. He's local here in Portland, so if I hear back from him, I'll arrange to meet up in person with him so he feels more invest in the project.]

**Comment by jywarren** [comment]
Also lots of laser cutting shops do glass cutting, so there should be other
options for plain writing onto mason jars -- no coozies, sadly.

**Comment by jywarren** [comment]
could do the drawn logo or the design from the tshirt I posted in #2

**Comment by BeckiC** [comment]
I'm dropping the cork coozie idea and going back to the silicone pint glass. I love the coozies but the guy who we were talking to about making them is taking 1-2 weeks to respond to REALLY basic emails about quantity, etc, even with reminder emails, which is just unacceptable.

**Comment by mathewlippincott** [comment]
at that scale I think the seal on the notebook would look better.

**Comment by jywarren** [comment]
yay fun:

![screen shot 2014-10-08 at 5 03 22 pm](https://cloud.githubusercontent.com/assets/24359/4567193/ea018da0-4f2e-11e4-90ec-145b28b945d8.png)![screen shot 2014-10-08 at 5 04 12 pm](https://cloud.githubusercontent.com/assets/24359/4567192/e9fbb18c-4f2e-11e4-98e6-7cec82a0b918.png)

**Comment by mathewlippincott** [comment]
the blue.  Yes! Yes!

**Comment by jywarren** [comment]
pantone PMS 2736

**Comment by jywarren** [comment]
sending vectors to Becki

**Comment by BeckiC** [comment]
Hey all! Looking at the images Jeff sent, I'm still a little concerned that image needs to be cleaned up a bit if folks are going to be able to recognize some of the things on there. What do either of you think about using the tshirt design for the pint glass? Maybe the colored-in version? The tshirt printers I've spoken with so far have both said that the outline-only version will work better on a shirt, so maybe we use the filled-in version on the glass? Shannon had also brought up the point earlier about having some consistency across goodies, which I think is relevant.

**Comment by jywarren** [comment]
I think it could work; it'd be good to see a mockup, though!

**Comment by BeckiC** [comment]
Hi Jeff! I sent the SiliPint guy the pdf of the Assemblage image (the filled in version) and he said he needs an .AI or .EPS format of it to do a mock up. Do you have that? I don't see those formats in the Dropbox file.
