### ISSUE TITLE
Add text to Infragram pic for Store carousel

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/design#10]
Can you please add text for this home page pic?
![carousel-item-3](https://cloud.githubusercontent.com/assets/7808557/4797537/67bba65e-5e0c-11e4-8380-d2a993f820e9.jpg)

**Comment by jywarren** [comment]
![infragram-banner](https://cloud.githubusercontent.com/assets/24359/4797805/71340c6a-5e0e-11e4-9051-59b0d279a205.jpg)
