### ISSUE TITLE
Holiday Promotion ads/graphics

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/design#11]
Hi team,

Just want to put this in your head, for when you have free draw time.
-ala Mathew- "Is that Spectra of light from Santa's sleigh? Or fumes from the coal plant? Let's find out with or Smartphone Foldups from Public Lab"
- a Public Lab sustainer membership is the gift that keeps on giving, and better than a Jelly of the month club.
  -This New Year, turn over a New Leaf and see it through the eyes of an Infragram Point and Shoot. Plot that leafs health and growth chart in the Infrared.

**Comment by jywarren** [comment]
what formats and sizes would these be in, and what venues would they be run in? print, digital, as website banners or on webpages? Sorry for the delay getting to them!

**Comment by Nataliegurl** [comment]
186px square, and 560px w x 280px h, jpg, Soundes emails, Shopify store
carousel/product pics, digital, one banner, one as kits button on home page.

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by jywarren** [comment]
So would these be primarily images, below which would appear the text you've suggested above? What kind of imagery?

**Comment by Nataliegurl** [comment]
Yes exactly,

mostly images I can attach to promotional emails and contacts. We need to
update the home page button for kits to have something. Something holiday
themed (either generic, or with kits pictured), festive, I'm open to
creative license. Text can be like above or just something along the lines
of "specials through the month of December, find out at store.publiclab.org"

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_
