### ISSUE TITLE
End of Year donation appeal flyer to include in Kits shipments

### ISSUE THREAD

**Issue by BeckiC** [publiclab/design#12]
I'm going to be drafting text for a end of year donation appeal flyer to include in all kits shipments between now and the end of the year. I'd appreciate any help on formatting. I'll link to text once it's drafted. Thanks!

**Comment by jywarren** [comment]
Happy to format once you have the text. Rad.

**Comment by BeckiC** [comment]
Support Public Lab with a year end, tax-deductible donation! 

Did you know that Public Lab is an open community supported by a nonprofit? Show your commitment to empowered, healthy communities by donating to Public Lab today. As a nonprofit organization, Public Lab relies on contributions from individuals like you. These donations allow us to design innovative hardware and partner with communities suffering from pollution to demand accountability.

Enjoy our products? Interested in supporting our work? This holiday season, donate to Public Lab! Give online at www.publiclab.org/donate or donate by check using the form below. 

Thanks, in advance, for your contribution, and happy holidays!

---

NAME:
ADDRESS:
CITY:
STATE:
ZIP:
COUNTRY:
EMAIL:
GIFT AMOUNT:

---

Public Lab is a 501(c)(3) non-profit corporation. Donations are tax deductible as permitted by law

**Comment by BeckiC** [comment]
Bump bump bump! Jeff, we need this ASAP so we can get them in kits shipments for the next couple weeks. Thanks!

**Comment by jywarren** [comment]
OK - I recommend printing on a thick piece of linen card paper, in black ink -- the design will be saved in /plots/design/2014-12-08-donation-kits/ once I'm done -- what mailing address do you want them to send it to?

**Comment by BeckiC** [comment]
Mail to:  Public Lab
412 NW Couch Street
#401
Portland, OR 97209
