### ISSUE TITLE
Ads for professorblue.com

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/design#15]
We are setting up a drop ship relationship with them similar to Scistarter, Science Cheerleader ads.
We could probably use the same ones for both. If I just need images and product info I will copy and send from the store. But I may need different images so FYI on you radar at some point.

**Comment by Nataliegurl** [comment]
Ping

**Comment by jywarren** [comment]
Hi, Natalie - did you look at the scistarter ones? https://github.com/publiclab/design/issues/9#issuecomment-66828385

What do you think? If you need different images and text, add them here and I can modify them. Thanks!

**Comment by Nataliegurl** [comment]
Okay, yeah I think they should work. I've sent and will see what they say,
if we need anything else. Thx

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_
