### ISSUE TITLE
Cobranding for KAPTERY kits

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/design#18]
We need another sticker label similar to the MultispeQ. By the Kaptery, brought to you by Public Lab etc.

![redstone pica](https://cloud.githubusercontent.com/assets/7808557/6253348/8764e3f6-b755-11e4-8d8c-6ee5ae5b1dcb.png)
(I would like all incubated kits done in green if possible)

Parts list for Redstone Rig:
http://fastie.net/kit-information/redstone-rig/redstone-parts/

Can we also add a check box on the label that says "suspension kit(s) included?"
Because this will be an option/variant for folks to order I'd like Noah to be able to indicate on the label if this is included.

**Comment by jywarren** [comment]
@Fastie - can you provide the following?
- a 24 character or less subtitle for what it does or is
- an 8 or fewer item list of parts inside the kit
- a 3d model I can open in sketchup, and/or a vector (pdf, csv) export of the rig from a couple angles (the pictured angle is pretty great)

Thanks!

**Comment by Fastie** [comment]
- "Aerial camera bracket" (19+2 characters)
- Included:
  1. 3D printed parts
  2. Legs and bumpers
  3. Hardware
  4. Tripod thumb screw

Except that many orders will also include a Picavet Kit and/or Pendulum Kit. So the list could be immediately followed by some check boxes:
- Redstone Rig Kit
- Picavet Kit
- Pendulum Kit

Or combine parts list and check boxes:
- Redstone Rig Kit
  1. 3D printed parts (4)
  2. Legs and bumpers
  3. Hardware
  4. Tripod thumb screw
- Picavet Kit
  1. 3D printed cross
  2. Lacing line
  3. Hardware
- Pendulum Kit
  1. Fiberglass shaft
  2. Flexible connector
  3. Hardware

This all depends on how kits, packages, and variants will be handled.

There are [some other photos here](http://publiclab.org/notes/cfastie/03-27-2014/the-redstone-rig-is-ready). I will send you the Sketchup file for this mockup.
![redstonemock](https://cloud.githubusercontent.com/assets/1805899/6259623/c9b48a84-b7a2-11e4-9af3-51f1615f999b.jpg)

.  
![picavetmock](https://cloud.githubusercontent.com/assets/1805899/6259451/bcf0d386-b7a0-11e4-88eb-745348bae84e.jpg)

**Comment by Nataliegurl** [comment]
That works, unless it gets too cluttered our we run our of room. Then I
would just list the redstone parts and two checkboxes for Picavet or
pendulum.

**Comment by jywarren** [comment]
In dropbox/plots/retail/universal-boxes/redstone/

**Comment by jywarren** [comment]
erg! not that!

this:

![screen shot 2015-02-23 at 12 20 23 pm](https://cloud.githubusercontent.com/assets/24359/6332827/7318b0e4-bb56-11e4-8811-a54728583666.png)
