### ISSUE TITLE
Sticker label for Pole Kits 1.2"x13"

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/design#19]
@jywarren @mathewlippincott 
from our brainstorm:
Need 25 sticker labels. These are basically rectangle stickers we are using to cover the the CARP Gangster part of the outside pole label. I think they would be cool if there were 25 individual stickers with pole "names" e.g. "the drone swatter," "selfie shamer," "longest selfie pole ever." and of course somewhere on there they should say, brought to you by Public Lab. Ideas for more pole names? Or just one really cool one. I don't know what the cost will be for individual stickers but its worth investigating I think.

**Comment by mathewlippincott** [comment]
How about this? I made it black to match the pole.  in design 3-23-15-mapping-pole-sticker
![screen shot 2015-03-23 at 3 35 40 pm](https://cloud.githubusercontent.com/assets/1203280/6792139/69b95bca-d172-11e4-9d82-afc0b2391ed4.png)

**Comment by jywarren** [comment]
haha rad :-)

On Mon, Mar 23, 2015 at 6:37 PM, mathew lippincott <notifications@github.com
