### ISSUE TITLE
T-shirt

### ISSUE THREAD

**Issue by jywarren** [publiclab/design#2]
1. Tshirt ($100 level, I'd mentioned this to Jeff before, I think it's on his to-do list. We're probably going to print these on demand via Zazzle or something so we dont have to dump a bunch money until we know people will want them)

**Comment by ebarry** [comment]
grey with all-over print of "I'm sorry but we don't have imagery at this zoom level, please contact Public Lab"

**Comment by mathewlippincott** [comment]
I don't know that we can do all-over print cheap enough to make that worth while. I believe 14x17 is the best we can do-- but a quick google search turned up a bunch of screen printers doing all-over now.  That wasn't the case in 2011, the last time I looked.
here's one:
https://www.realthread.com/services/print-sizes/standard-size-screen-printing

For running them as one-offs, I think Jak prints has the cheapest all-over (inkjet on polyester) its $35 for a one-sided shirt.  Ouch.
http://www.jakprints.com/all-over-shirt-printing/

**Comment by BeckiC** [comment]
Yup, all over print is too expensive. We need to look at options that are
between $10 and $20 to print on demand. To clarify, I'll take lead on
sourcing, I'm asking for help from the design team regarding what to put on
the shirt that is cool and in line with how y'all are planning our larger
branding strategy.

## 

Becki Chall
Development Manager
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by jywarren** [comment]
OK, i did a bunch of work on one design that didn't go anywhere fast... maybe will try to resuscitate it later, but I just had a brain spark and did this one. It would require 2 colors, although we could do it in 1 color if need be. 

![pl-shirt2](https://cloud.githubusercontent.com/assets/24359/4561888/7bddbaca-4f00-11e4-8826-47f043ef5d61.png)

**Comment by BeckiC** [comment]
Cool--it could look nice in 1 color as well. If you want to take some time over staff meeting to work on/refine this since that week might be a little more relaxed, that's fine as well.

**Comment by mathewlippincott** [comment]
that looks really good.  I don't think it needs refining. I like how rough it is.

**Comment by jywarren** [comment]
more variations. Shannon mentioned she'd like to see a version with formal type. I wanted to try a few different things. I like the original best, but could imagine a more tightly hand-lettered version working. 

![screen shot 2014-10-08 at 2 20 31 pm](https://cloud.githubusercontent.com/assets/24359/4564582/c484dd54-4f18-11e4-8149-709e6de0d372.png)
![screen shot 2014-10-08 at 2 24 47 pm](https://cloud.githubusercontent.com/assets/24359/4564580/c47a4dda-4f18-11e4-8580-26501ad4723c.png)
![screen shot 2014-10-08 at 2 15 22 pm](https://cloud.githubusercontent.com/assets/24359/4564581/c47e8710-4f18-11e4-9fc1-5bcb768e0506.png)
![screen shot 2014-10-08 at 2 18 45 pm](https://cloud.githubusercontent.com/assets/24359/4564583/c487282a-4f18-11e4-9dd5-27c1fd98f442.png)

**Comment by mathewlippincott** [comment]
I actually like the original, scrappy letters the best, second best is the new hand letters, after that the flat, non-outlined cursive.

**Comment by BeckiC** [comment]
I really like the overall concept of the shirt, including the hand drawn
text! I do think, however, the drawing needs to be cleaned/neatened up a
bit, though, so that its clear to people outside the "inner circle" what
the objects on the shirt are. Maybe swap some of the more ambiguous ones
out for something more readily identifiable--a kite or something. I want a
shirt design that we all feel super excited to wear, but also, for example,
that I could give to my dad and he could rock it and explain to people what
the shirt and PL are about. Remember, the shirt is associated with a $100
membership pledge, so we want to make sure it looks sharp and our brand of
awesome.

## 

Becki Chall
Development Manager
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by jywarren** [comment]
other more graphical/textural ideas. i'd be more into dropping specific recognizable items, as I think they are more likely to be relevant to "insiders". i have more in my sketchbook and we can iterate/develop more this coming week.

![tshirt-waves-diag](https://cloud.githubusercontent.com/assets/24359/4604170/7f79cfd4-518a-11e4-80cf-23f35c1d6917.jpg)
![tshirt-waves](https://cloud.githubusercontent.com/assets/24359/4604168/7f774886-518a-11e4-9535-3c4659c56a60.jpg)

**Comment by jywarren** [comment]
more!
![shirts-3](https://cloud.githubusercontent.com/assets/24359/4669186/a6633eca-556b-11e4-9f7c-aab6c2029651.png)
![shirts-4](https://cloud.githubusercontent.com/assets/24359/4669163/7363cf58-556b-11e4-87b6-b514a164d639.png)

**Comment by jywarren** [comment]
Another!
![shirt-assemblage](https://cloud.githubusercontent.com/assets/24359/4687612/b40b5a24-5658-11e4-9d95-34a7aa20a22d.png)

**Comment by sdosemagen** [comment]
Like. The lettering is a little strange, but the design is really clear as to what it is.

**Comment by jywarren** [comment]
@mathewlippincott also had some good pointers on tweaking/improving the shirt details, like the carabiner and DVD. Text was the part I was least happy with; can retry it for sure.

**Comment by BeckiC** [comment]
I echo what Shannon said about the latest design. I really like that one as
well as the top left of the four you sent out previously.

## 

Becki Chall
Development Manager
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by jywarren** [comment]
If there's a concern about the amount of ink making the shirt creas-y, we could do this version (also see for text changes) but I think the white backing really makes the shirt pop. Threadless prints a bit lighter-weight with their inks, so if we get a good printing job I don't think the extra ink will be a problem, and I prefer the light grey backing. 

![screen shot 2014-10-23 at 5 12 59 pm](https://cloud.githubusercontent.com/assets/24359/4761593/a2a9214e-5af9-11e4-8cf9-883a35bc0b5e.png)

**Comment by jywarren** [comment]
Oops, wrong image; W/ white backing on text -- maybe the text should be completely redrawn though:

![screen shot 2014-10-23 at 5 20 59 pm](https://cloud.githubusercontent.com/assets/24359/4761729/9b7efd2a-5afa-11e4-990f-9316129c58c2.png)

**Comment by BeckiC** [comment]
I like them both though am a bit concerned about the stiff shirt issue. If
we like the design, we could order one of each from Zazzle or a similar
site on a nice Threadless-weight shirt and see what we think?

## 

Becki Chall
Development Manager
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by jywarren** [comment]
Sounds good to me -- can we get input from a screenprinter on the ink
weight and stiffness? I'm worried Zazzle won't be good quality.

**Comment by BeckiC** [comment]
Sure, I'll run it past my friend Will.

## 

Becki Chall
Development Manager
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by BeckiC** [comment]
Hey Jeff, 

Is there a good AI or EPS image of the filled in tshirt design? I want to send it to the silicone pint glass guy to see about getting a mockup, and shop it around a bit in Portland to see what options we might have locally since the mason jar guy flaked on me. Thanks!

**Comment by jywarren** [comment]
yes, there should be a PDF in the Dropbox folder something like
/plots/design/xx-xx-xx-tshirt

**Comment by BeckiC** [comment]
Will the assemblage image in the pint glass folder work for a pint glass
mock up given it has the tshirt color behind it?

https://www.dropbox.com/s/wdp7gso6upauyp7/assemblage.svg?dl=0

Or is there a file of just the design that I'm not seeing? Sorry, I'm just
not familiar enough with this to know what's appropriate to send.

Thanks!

## 

Becki Chall
Development Director
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by jywarren** [comment]
Yes, its vector so they'll be able to remove the background easily.

**Comment by BeckiC** [comment]
Hey Jeff,

Is there a vector image of the outline only version with the original (3-d,
not flat stretched) text? I think that's the version I'd like to use. I had
sent the printer a version in a lower quality format and it appears sort of
blocky once it's sized up for the shirt.

Thanks!
Becki

## 

Becki Chall
Development Director
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by BeckiC** [comment]
Proof here:
https://www.dropbox.com/s/o1pe6q0udz7a4a4/Lab%20Equipment%20PROOF.pdf?dl=0

## 

Becki Chall
Development Director
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by jywarren** [comment]
Closing this for now as they've been printed
