### ISSUE TITLE
5th Anniversary Lead image for carousel in store

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/design#21]
Along with the Pole Mapping Kits. I don't know what graphics or images are being used for the fundraising or comdev teams but the same could be used for this. I think it will help with consistency or a unified message.

**Comment by jywarren** [comment]
OK, is next monday (10 days from now) all right? Do you have specific text etc? Perhaps you can circle back with liz, stevie or becki about what they're doing?

**Comment by Nataliegurl** [comment]
I think "Celebrate 5 years with Public Lab" works. 'All Mapping kits on sale all month long." If there is a better way to incorporate this too...

**Comment by jywarren** [comment]
Where would it lead when people click on it?

**Comment by Nataliegurl** [comment]
The Mapping Kits collections page

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 307Portland, OR 97209_

_T: 971.570.5095_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by jywarren** [comment]
How about this?

![kits-banner-dark](https://cloud.githubusercontent.com/assets/24359/7120480/6ffbbae0-e1db-11e4-959a-56f941086819.png)
![kits-banner](https://cloud.githubusercontent.com/assets/24359/7120481/6fff612c-e1db-11e4-9fff-7693dcaa9921.png)

**Comment by jywarren** [comment]
I can crop to size if you like.

**Comment by Nataliegurl** [comment]
Yeah! The top one is easier to read

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 307Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_
