### ISSUE TITLE
MultispeQ co-branding w/Public Lab (revisited)

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/design#22]
The PhotosynQ peeps came up with a new logo that is pretty cool. I would like to use this for our co-branding labels as soon as you get a chance. If you could do another version that says "PhotosynQ" directly below the logo, I would like to print 3x3 square stickers as well.

![logo 512](https://cloud.githubusercontent.com/assets/7808557/7078057/a58eaf46-deca-11e4-87a5-acdffcf37de5.png)
![icon 512](https://cloud.githubusercontent.com/assets/7808557/7078059/a796410a-deca-11e4-9847-d6c59c04e444.png)

**Comment by jywarren** [comment]
Hi, Natalie - can you get a vector version of that, in svg or pdf?

**Comment by jywarren** [comment]
Vector: https://www.dropbox.com/sh/f96xpyi9i34bpv3/AAA8zU3XJKuBQY_RKxBwc93na?dl=0

new versions in /plots/retail/universal-boxes/photosynq/
