### ISSUE TITLE
Paper Research Note(pads)

### ISSUE THREAD

**Issue by ebarry** [publiclab/design#5]
The pads on Zazzle come as sticky Post-It style notes costing ~$280 for a minimum quantity of 48, and they don't have a cover--we'd have to affix that ourselves. I think we need to approach a printer about less fancy tear-off pads with covers. 

Cover Illustration: 

![why write research notes](https://cloud.githubusercontent.com/assets/161439/4413593/34bdcfde-4507-11e4-8643-151ece715321.png)

Custom printed notepads: 
![paper-research-note](https://cloud.githubusercontent.com/assets/161439/4413599/41e6870a-4507-11e4-8ec0-7d56e0a6f03c.jpg)

**Comment by ebarry** [comment]
The printing on the post-it pads from Zazzle is a little blurry. New plan is to work with Charles the Portland printer to get plain paper notes printed at 3 - 4 cents per page, then send them off to get "perfect bound with a chipboard back cover and a printed front cover. Should be cheaper than working with Zazzle. Estimated 10 day turnaround once placing the order.

**Comment by ebarry** [comment]
Wire binding is also an option, with chipboard cover and backing. 
Proposed dimension of 5.5" x 8.5"
Still being resolved is whether the hand drawn version of the pages can work as is (http://i.publiclab.org/system/images/photos/000/007/037/original/paper-research-note.jpg) or will need to be redrawn somehow but not fully vectorized like http://i.publiclab.org/system/images/photos/000/005/810/original/PaperResearchNote_picturespace.pdf

**Comment by ebarry** [comment]
OK @jywarren contributed the vector version of the hand-drawing: http://i.publiclab.org/system/images/photos/000/005/815/original/paper-research-note.pdf

Planning a run of 100 5.5"x8.5" wirebound books, with chipboard printed front and blank back covers, each containing 60-80 pages of 60# paper printed single side with the research note drawing. 

Does anyone want the ink to be a color other than black? or to have a second color on the front cover? Hardly any price difference.

**Comment by mathewlippincott** [comment]
can we do a light blue background for the black ink?

**Comment by mathewlippincott** [comment]
I mean on the cover.  I think b&w is best for the inside

**Comment by jywarren** [comment]
Dark blue ink on a light blue background, both somewhat low saturation,
would look great.

On Wed, Oct 29, 2014 at 1:37 PM, mathew lippincott <notifications@github.com

**Comment by ebarry** [comment]
Sounds great. I'll check with Charles. Just curious though, is the blue
theme related to anything else currently going on graphically in Public Lab?

## 

@lizbarry http://twitter.com/lizbarry

**Comment by jywarren** [comment]
Nope, just riffing on your suggestion of blue.

**Comment by ebarry** [comment]
There aren't many options for light blue paper on the cover. In Charles' words:
"inexpensive 65# cover stock (which is okay but not very thick) or a more expensive grade of paper in 80#, such as Classic Crest, smooth or linen. I think Mohawk Via also has a light blue sheet in 80#."

So am making the call to keep the front cover as chipboard (as is the back cover) and we'll print on it with dark blue ink. 

What else do we want on the front cover besides the 4 circles of the "Why write research notes" illustration? (the publiclab logo? Maybe that goes on the back cover.) We could include text like "Paper Research Notepad, first edition: Barnraising 2014", and put a line for people to write their name. 

Any opinions on how think of a wire-bound pad it should be? It's looking like a 1/2" will be good. 

Currently, the back of each of the pages (white, 60#) will be blank. Let me know if you have other ideas.

**Comment by jywarren** [comment]
If it's chipboard, can you print in white or black? There's a collection of
design ideas in /plots/retail/packaging-ideas/ -- not a big deal, but for
consistency's sake.

**Comment by ebarry** [comment]
I"ll check out that folder, thanks! How about white ink on the cover?

**Comment by jywarren** [comment]
ask! charles has said he has trouble getting white ink to show, and has
recommended screenprinting that in the past. But maybe it's paper dependent?

**Comment by jywarren** [comment]
These turned out great. Closing unless any additional tweaks?
