### ISSUE TITLE
Blank Waterproof Pocket notebook

### ISSUE THREAD

**Issue by BeckiC** [publiclab/design#6]
Eberhardt can print--nice off-brand paper, good cover material. Red cover with white image + rulers on back for easy reference. What cover art?

**Comment by jywarren** [comment]
I really liked how the decal image ran in white on a red cover, as in the email I sent:

![screen shot 2014-09-23 at 6 00 34 pm](https://cloud.githubusercontent.com/assets/24359/4561928/c1511ae8-4f00-11e4-8b19-f346443945e1.png)

I think the pdf I included on that email is good to go, if that looks good to you. We can ditch the "Public Lab" if you don't like it. 

We could also do something similar to the shirt art I just posted in #2

**Comment by BeckiC** [comment]
Great--let's ditch the "Public Lab" and I think it will be good to go. Do we want to do rulers on the back or no? I don't have a strong preference either way.

**Comment by jywarren** [comment]
I like the rulers. Need artwork for that too, right?

**Comment by BeckiC** [comment]
Yup!

## 

Becki Chall
Development Manager
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by mathewlippincott** [comment]
I ran a modified version of this chart on the second GMF as a photo scale, it can be used to rectify an image too.  Great for taking field shots of samples and looks cool. What do you think?

![refscale_3x](https://cloud.githubusercontent.com/assets/1203280/4563727/76d7b826-4f11-11e4-84ae-bb4a27cb4cd7.jpg)

I made a high-res photoshop version here that could be modified quickly, I could do it too.
grassrootsmappingforum/issue-2/gmforum/summer2012/scalechart

**Comment by jywarren** [comment]
![screen shot 2014-10-08 at 2 32 48 pm](https://cloud.githubusercontent.com/assets/24359/4564694/9b5b8774-4f19-11e4-8cdc-72d1dc9ef3a8.png)

I like what Mathew posted. Might look like this:

![screen shot 2014-10-08 at 2 57 49 pm](https://cloud.githubusercontent.com/assets/24359/4565119/15e1d018-4f1d-11e4-9969-3d067462d10f.png)

Mathew, do you think Charles can print with the raster version of the scale chart? What was the final size he could do? Can he do rounded corners?

**Comment by mathewlippincott** [comment]
yup, he can do rounded corners.  let me reach out to him on the final size-- he sourced that tiger paper since we last talked sizes.

**Comment by jywarren** [comment]
the ruler is CC-NC, so I looked for another more open one; this one is CC-zero: 

https://commons.wikimedia.org/wiki/File:Echelle_mm_cm_pour_photo.svg

![ruler](https://cloud.githubusercontent.com/assets/24359/4595538/bc384c70-509a-11e4-9b28-be2f469cc2de.png)

**Comment by jywarren** [comment]
do we like the drawn seal (bootier version), the tshirt draft, or the kite-flying-thing from the first mockup I did?

**Comment by BeckiC** [comment]
I like the kite flying thing, like we used for the decal.

## 

Becki Chall
Development Manager
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by jywarren** [comment]
ok, pending paper size but I laid it out in the same as Field Notes books; 5.5x3.5 - it's in the /plots/design/ folder

**Comment by mathewlippincott** [comment]
We talked back and forth about it-- final size is 4.75x3.25.  remember that "centered" has to account for the rounding of the binding, so more like a right-justified 3.125" cover, if you want to get particular.

**Comment by mathewlippincott** [comment]
we're going to do 32 pages.

**Comment by mathewlippincott** [comment]
nice call on the CC zero chart. weird to have someone else's url on our notebook

**Comment by mathewlippincott** [comment]
OK we can't use Tiger Paper... Have to order too much for the quantities we're doing.

We are going to try Yupo, that comes in the quantities we want. Charles recommends 57lb text and 100lb cover, told us we have to order our own samples.  I'm not sure where we order a single page of exactly this paper.  Their watercolor paper comes in 10 packs but I don't know if that will have the same ink response, which is what I really want to know.

https://www.shopyupo.com/product.php?productid=16201&cat=274&page=1

Https://www.shopyupo.com/product.php?productid=16198&cat=274&page=1

**Comment by mathewlippincott** [comment]
I contacted them for samples.

**Comment by mathewlippincott** [comment]
they didn't get back to us about samples so I bought a ream of 57lb text weight ($77).  I'm holding off on the cover stock until we see we really want to write on this stuff.

**Comment by mathewlippincott** [comment]
OK-- the waterpoof Yupo works pretty well-- pencil, ballpoint, and sharpie (solvent-based) pens write fine.  Gel pens, felt tips, and water-based pens don't dry quickly and will smudge up to 10 minutes after writing.  Its not ideal, but its pretty damn good and recyclable. We're going to order the cover stock and go for production

Final details:
32 pages
rounded corners
ruler on back
printing on inside cover with details on pens, recycling, materials the notebook is made of

So ToDos:
1)Order 100lb cover stock in 8.5x11 size
https://www.shopyupo.com/product.php?productid=16198&cat=274&page=1

3) a warning for the inside front cover or back outer cover that says: pencil, ballpoint and permanent markers work great, we don't recommend water-based and gel pens.  This notebook is made from 100% Polypropylene (5)[symbol] YUPO paper, manufactured in the USA.  please recycle. 

OPTIONAL:
4) A CERN open hardware license on the inside back cover? with a place to download the notebook print files? (I think this would be excellent)

5) include inches in the ruler on the back?

**Comment by jywarren** [comment]
+1 all sounds rad.

**Comment by mathewlippincott** [comment]
looks like we just re-did field notes R&D, lol:
http://fieldnotesbrand.com/colors/expedition/

**Comment by mathewlippincott** [comment]
updated, in same folder design/10-8-14-blank-notebook

still nothing on back inside cover.... should we add something?  CERN license is rediculous, doesn't fit at all at any legible size.

![screen shot 2014-12-08 at 6 01 38 pm](https://cloud.githubusercontent.com/assets/1203280/5351061/5905d59e-7f04-11e4-86ce-8cc0e22f403e.png)

![screen shot 2014-12-08 at 6 01 27 pm](https://cloud.githubusercontent.com/assets/1203280/5351062/5b67932c-7f04-11e4-810f-780bafc0ee23.png)

**Comment by jywarren** [comment]
Very lovely! I like it a lot.

Maybe back inside cover: http://publiclab.org/wiki/kite-mapping-tips

Dunno. Or that could go in the front inside and the text from the front
could go in the back? Anyways it looks super.

**Comment by mathewlippincott** [comment]
Take 2.  I made the back a little flashier as a photo target, and moved the interior info as jeff suggested.  thoughts?

![screen shot 2014-12-09 at 2 20 51 pm](https://cloud.githubusercontent.com/assets/1203280/5367168/9e0d8c04-7fae-11e4-964c-37f5e992e277.png)

![screen shot 2014-12-09 at 2 20 22 pm](https://cloud.githubusercontent.com/assets/1203280/5367175/a1892168-7fae-11e4-86d7-93df50fdb98f.png)

**Comment by mathewlippincott** [comment]
garish or stylish? I know the color is a little off of our mock-up.

![screen shot 2014-12-10 at 9 53 03 am](https://cloud.githubusercontent.com/assets/1203280/5381055/870df8e6-8052-11e4-8774-4d63c805d06d.png)

**Comment by BeckiC** [comment]
Not quite garish or stylish--functional.

## 

Becki Chall
Development Director
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

On Wed, Dec 10, 2014 at 9:54 AM, mathew lippincott <notifications@github.com

**Comment by mathewlippincott** [comment]
if we can't do a full-color print-- like all red over the white, what other color directions do we want to go in?  running tests with charles now.

**Comment by BeckiC** [comment]
I like black and white but if we think that's too boring, I'm open to
suggestions.

## 

Becki Chall
Development Director
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

**Comment by Nataliegurl** [comment]
black and white +1
or
black and red!

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by mathewlippincott** [comment]
Charles doesn't think the color is going to be an issue.

**Comment by BeckiC** [comment]
Did he have an ETA on printing them?

## 

Becki Chall
Development Director
Public Laboratory for Open Technology and Science
810-287-3940
www.publiclab.org http://www.publiclaboratory.org/

_Love our work? Become a Public Lab Sustaining Member
http://publiclab.org/donatetoday!_

On Tue, Dec 16, 2014 at 1:11 PM, mathew lippincott <notifications@github.com
