### ISSUE TITLE
slides for big screen in the OMSI store

### ISSUE THREAD

**Issue by jywarren** [publiclab/design#8]
@Nataliegurl  sez: I need to get a slide made that we can display on the big screen in the OMSI store. This is a great opportunity to generate more interest and also drive sales. We can switch them out from time to time as well. I'm working on some of our holiday promotion approaches but for now I would like something that is minimal but gets people interested. Something like, "what can you do to help the environment" "get involved at public lab" "now available in the OMSI store" "Diy plant monitor made easy" just some ideas.

Also, if there is a way to tie in the KS I'm definitely behind it.

For the slide I need a high resolution JPEG, dim. 1920x1080

Is this something you can make time for this week or soonish?

**Comment by jywarren** [comment]
@Nataliegurl - when would these go live, assuming we had them in time? Would the KS lead image with the lasers and sample jars be appropriate, or not, because they don't stock the HOTK? Maybe something based on these smartphone spectrometer or foldable spec images: 

![smartphone_1024x1024](https://cloud.githubusercontent.com/assets/24359/4566163/6810dc5e-4f26-11e4-97e3-338769aebb2f.jpg)
![cd83273f6a0024d0e88f928778b63f52_large](https://cloud.githubusercontent.com/assets/24359/4566162/68075f30-4f26-11e4-9577-311beace2072.jpg)

The latter image here should be used on the store anyhow. 

It'd be great to stage a very nice Infragram Webcam image which shows a plant, a live image of it on a laptop screen next to it, and the webcam itself pointing at the plant.

**Comment by Nataliegurl** [comment]
Live within the week or as soon as I can get them sent, it wouldn't be
long. I agree with both statements. The Foldup slide should be there with a
little bit of text added along the lines of what I suggested. And yes to
the Infragram staging as well.

I think the KS lead image might work if we change the text. Have it
centered around the sprectrometer as the the basis, then add something at
the bottom, "by the way, KS"

Doe that make sense. Then when people follow through to the kick starter
the lead image will be a trigger/reminder.

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by jywarren** [comment]
I like the idea of teasing the KS, but our conversion rate from a screen in
the store probably isn't going to be great; maybe we should just focus on
some nice images that'll last a while.

**Comment by Nataliegurl** [comment]
Whatever you think is best. I agree the conversion rate won't be huge, it's
just a little added coverage, but the KS will be over and we'd have to
update it.

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by jywarren** [comment]
![foldable-1920x1080](https://cloud.githubusercontent.com/assets/24359/4568575/aaa4253e-4f3b-11e4-903e-7c37f7b65136.jpg)

**Comment by jywarren** [comment]
![smartspec](https://cloud.githubusercontent.com/assets/24359/4568709/30727002-4f3d-11e4-9ce3-e58359c4290e.jpg)

**Comment by Nataliegurl** [comment]
These look great! The smartphone spec isn't in store though, just the
Foldup. I would really like one for the Infragram as well. To date we've
only sold one of those at the store, and I would like to give it some more
attention.

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by jywarren** [comment]
Which infragram?

**Comment by Nataliegurl** [comment]
The webcam.

**Comment by jywarren** [comment]
![infragram-2](https://cloud.githubusercontent.com/assets/24359/4583005/d98cd460-4fed-11e4-942d-2e1a62bc55a2.jpg)
![infragram-1](https://cloud.githubusercontent.com/assets/24359/4583003/d98216a6-4fed-11e4-819d-ac1c1d71570f.jpg)

**Comment by jywarren** [comment]
actually this image is rad 

![infragram-3](https://cloud.githubusercontent.com/assets/24359/4583925/61b0b7fa-4ff6-11e4-8c0d-6f37bb717ef4.jpg)
![infragram-3b](https://cloud.githubusercontent.com/assets/24359/4583926/61bde434-4ff6-11e4-81ab-f284adf5f4c3.jpg)

**Comment by Nataliegurl** [comment]
That is super cool! Actually, Mathew just pointed out though, are those
images taken with the P&S? I think we need images taken with the filter
from the webcam? Does that make red leaves?

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by jywarren** [comment]
do you have any IG webcam images that are as rad as these?

**Comment by Nataliegurl** [comment]
Can we grab any of these?
http://publiclab.org/notes/ivalethia/09-20-2014/first-infragram-cam-trials-primeros-ensayos-con-camaras-infragram

http://publiclab.org/notes/cfastie/09-19-2014/leaffest-aerials

Mathew probably has more on this than I do.

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by Nataliegurl** [comment]
Just bring this back to the top. Do we have a status update on the sweet Infragram pic you found?

**Comment by jywarren** [comment]
yes, it's in plots/design/##-##-##-omsi-screen - take a look!

**Comment by Nataliegurl** [comment]
Nice!

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_
