### ISSUE TITLE
Ads for SciStarter and SciCheer

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/design#9]
I need a few ad type banners to run on the SciStarter and Science Cheerleaders website. This is what she sent me:

"Thanks, Natalie.
We have ads on each of the project pages so we can cycle through different product ads that way. We'll need the ads from you...200 x 200 image with appropriate links.
And, yes, we will push sales through science cheerleader and (possibly) at events. This is such a natural fit and hopefully a way for PL and SciStarter to generate some revenue!"

Can we work these up for the Inragrams, WheeStat, Foldups, and Balloon Kits?

**Comment by jywarren** [comment]
Hi, Natalie - i'm sorry, getting behind on this. Is it OK to do it next
week before the barnraising? I'm trying to get in order for the HOTK event
this weekend (w/ the awards)

**Comment by Nataliegurl** [comment]
Sure thing. As soon as you can get to it is fine.

**Comment by Nataliegurl** [comment]
Bump.

Any progress on this?

**Comment by Nataliegurl** [comment]
This would be a good to go along with our holiday/year end promotion.

**Comment by jywarren** [comment]
OK; i'd like to use this image, but could you ask Hagit? https://www.flickr.com/photos/fiestin/8441107262/

Here are four images: 

![balloonkit-200x200](https://cloud.githubusercontent.com/assets/24359/5418598/88102316-8211-11e4-95e6-d950431ec132.png) ![foldable-200x200](https://cloud.githubusercontent.com/assets/24359/5418600/88123142-8211-11e4-83c0-f7e0d92846a7.png) ![infragram-200x200](https://cloud.githubusercontent.com/assets/24359/5418601/8814bd90-8211-11e4-8686-9ad079291e66.png) ![infragram-b-200x200](https://cloud.githubusercontent.com/assets/24359/5418599/88110948-8211-11e4-9e5d-55c62c00be8b.png)

**Comment by jywarren** [comment]
The balloon image I did use was on this page: http://publiclab.org/wiki/new-york-city -- and I think you'll have to ask @ebarry where it's from so we can attribute it. The rest of the photos Mathew and I took.

**Comment by ebarry** [comment]
ok that was taken by Nick johnson --- Nick,what's the photo credit on this
image of your freshkills  Freshkills workshop?
 [image: Inline image 1]

## 

@lizbarry http://twitter.com/lizbarry

**Comment by jywarren** [comment]
If it's on the pl website, it's CC-BY-SA and we can put his username on it. What's his username?

**Comment by jywarren** [comment]
Natalie, did these work? Can we close this issue?
